"""
Adversarial QA test suite — generated by code-tester v3.1.0
Target: handwriting-engine
Mode: full | Depth: normal
Agents: Boundary Hunter, Scale Breaker, Interaction Prober
Date: 2026-04-10
"""

from __future__ import annotations

import math
import os
import tempfile
import pytest
from PIL import Image, ImageDraw


# ===========================================================================
# Fixtures
# ===========================================================================

def _solid_image(color=(200, 200, 200), size=(200, 200), mode="RGB", suffix=".jpg"):
    """Create a solid-color temporary image."""
    img = Image.new(mode, size, color)
    fd, path = tempfile.mkstemp(suffix=suffix)
    os.close(fd)
    if suffix == ".png":
        img.save(path, "PNG")
    else:
        if mode == "RGBA":
            img = img.convert("RGB")
        img.save(path, "JPEG", quality=95)
    return path


def _striped_image(size=(200, 200)):
    """Create a black/white striped image for blur/contrast tests."""
    img = Image.new("RGB", size, (255, 255, 255))
    draw = ImageDraw.Draw(img)
    for y in range(0, size[1], 10):
        draw.line([(0, y), (size[0], y)], fill=(0, 0, 0), width=2)
    fd, path = tempfile.mkstemp(suffix=".jpg")
    os.close(fd)
    img.save(path, "JPEG", quality=95)
    return path


# ===========================================================================
# T1 — Boundary Collision: quality module
# ===========================================================================

class TestQualityBoundaryCollision:
    """T1: Multi-dimensional boundary combinations on assess_* functions."""

    def test_assess_contrast_single_pixel_image(self):
        """TC-1: 1x1 pixel image — histogram has only 1 bucket; p95 loop must not crash."""
        from handwriting_engine.quality import assess_contrast
        img = Image.new("RGB", (1, 1), (128, 128, 128))
        # Must not raise; result in [0, 1]
        score = assess_contrast(img)
        assert 0.0 <= score <= 1.0

    def test_assess_contrast_all_midtone(self):
        """TC-2: All pixels at 128 — p5 == p95 == 128, range == 0."""
        from handwriting_engine.quality import assess_contrast
        img = Image.new("L", (200, 200), 128).convert("RGB")
        score = assess_contrast(img)
        # (128-128)/255 == 0.0
        assert score == 0.0, f"Expected 0.0 for uniform midtone, got {score}"

    def test_assess_blur_1x1_image(self):
        """TC-3: 1x1 image — Laplacian kernel (3x3) applied to 1-pixel image."""
        from handwriting_engine.quality import assess_blur
        img = Image.new("RGB", (1, 1), (0, 0, 0))
        # Should not crash (Pillow pads with edge extension)
        score = assess_blur(img)
        assert isinstance(score, float)

    def test_assess_contrast_p95_monotone_loop_bug(self):
        """TC-4: p95 loop iterates histogram forward (never backward), so for a
        fully-white image the cumulative sum hits total*0.95 at index 255.
        But p5 hits at index 255 too — range is 0, not negative."""
        from handwriting_engine.quality import assess_contrast
        img = Image.new("RGB", (100, 100), (255, 255, 255))
        score = assess_contrast(img)
        # p5 = 255, p95 = 255 → (255-255)/255 == 0
        assert score >= 0.0

    def test_assess_brightness_zero_size_raises_or_returns(self):
        """TC-5: Degenerate 0x0 image — ImageStat on empty may raise."""
        from handwriting_engine.quality import assess_brightness
        try:
            img = Image.new("RGB", (0, 0))
            mean, std = assess_brightness(img)
            # If it doesn't raise, values must be numeric
            assert isinstance(mean, float)
        except Exception:
            pass  # Either outcome is acceptable — just must not silently corrupt


class TestQualityBoundaryAssessImage:
    """T1/T2: Boundary and contract violations in assess_image."""

    def test_assess_image_nonexistent_path(self):
        """TC-6: assess_image with a path that doesn't exist."""
        from handwriting_engine.quality import assess_image
        result = assess_image("/tmp/__does_not_exist_codetester__.jpg")
        # Must return structured dict, not raise
        assert isinstance(result, dict)
        assert "quality" in result
        assert result["quality"] == "poor"

    def test_assess_image_empty_file(self):
        """TC-7: assess_image with zero-byte file."""
        from handwriting_engine.quality import assess_image
        fd, path = tempfile.mkstemp(suffix=".jpg")
        os.close(fd)
        # File exists but is empty — Image.open will raise UnidentifiedImageError
        result = assess_image(path)
        os.unlink(path)
        assert result["quality"] == "poor"
        assert "corrupt_image" in result["issues"]

    def test_assess_image_truncated_jpeg(self):
        """TC-8: assess_image with a JPEG missing its end-of-image marker."""
        from handwriting_engine.quality import assess_image
        # Write a JPEG header only (truncated)
        fd, path = tempfile.mkstemp(suffix=".jpg")
        with os.fdopen(fd, "wb") as f:
            f.write(b"\xff\xd8\xff\xe0" + b"\x00" * 20)  # Truncated JPEG
        result = assess_image(path)
        os.unlink(path)
        # Must not crash; should detect corrupt
        assert isinstance(result, dict)
        assert "quality" in result

    def test_assess_image_returns_skew_angle_key(self):
        """TC-9: Contract: assess_image must include skew_angle in result dict."""
        from handwriting_engine.quality import assess_image
        path = _striped_image()
        result = assess_image(path)
        os.unlink(path)
        # skew_angle was added in quality.py but NOT in the corrupt-path branch
        assert "skew_angle" in result, "Non-corrupt path must include 'skew_angle'"


# ===========================================================================
# T2 — Contract Violation: assess_contrast p95 logic bug
# ===========================================================================

class TestAssessContrastP95Bug:
    """T2: The p95 loop in assess_contrast iterates FORWARD through histogram.
    For images where < 5% of pixels are at the top of the range, p95 will
    be found correctly. But if cumulative sum at some index < 255 first reaches
    total*0.95, the break exits correctly. Edge case: what if all pixels are
    dark? p5 = 10, p95 should also be 10 → contrast = 0. Verify."""

    def test_all_black_contrast_is_zero(self):
        """TC-10: All-black image must have contrast 0."""
        from handwriting_engine.quality import assess_contrast
        img = Image.new("RGB", (200, 200), (0, 0, 0))
        score = assess_contrast(img)
        assert score == 0.0, f"All-black image should have 0 contrast, got {score}"

    def test_half_black_half_white_contrast_near_one(self):
        """TC-11: Half pixels = 0, half = 255 → perfect contrast → ~1.0."""
        from handwriting_engine.quality import assess_contrast
        img = Image.new("L", (200, 200), 0)
        arr = list(img.getdata())
        half = len(arr) // 2
        arr[half:] = [255] * (len(arr) - half)
        img.putdata(arr)
        img = img.convert("RGB")
        score = assess_contrast(img)
        assert score >= 0.9, f"Half-black/half-white contrast should be ~1.0, got {score}"

    def test_contrast_p95_invariant_dark_image(self):
        """TC-12: Very dark image — all pixels at 10. p5 = p95 = 10. Contrast = 0."""
        from handwriting_engine.quality import assess_contrast
        img = Image.new("RGB", (200, 200), (10, 10, 10))
        score = assess_contrast(img)
        assert score == 0.0


# ===========================================================================
# T3 — Expectation Inversion: quality thresholds
# ===========================================================================

class TestQualityThresholdInversion:
    """T3: Test the borderline between quality tiers."""

    def test_quality_exactly_at_blur_threshold(self):
        """TC-13: blur == BLUR_THRESHOLD (100) — the condition is blur < threshold,
        so exactly AT the threshold should NOT trigger 'blurry'."""
        from handwriting_engine.quality import assess_image
        from handwriting_engine._constants import BLUR_THRESHOLD
        # We can't control assess_blur precisely, but we can test the boundary logic
        # by mocking. Instead, verify the condition direction in code:
        # issues.append("blurry") only if blur < BLUR_THRESHOLD
        # So blur == 100 should NOT add "blurry"
        # Create a sharp image and verify
        path = _striped_image(size=(400, 400))
        result = assess_image(path)
        os.unlink(path)
        # Sharp striped image should score well above 100
        assert result["blur_score"] > BLUR_THRESHOLD, (
            "Striped image should be above blur threshold"
        )

    def test_quality_logic_single_issue_fair_boundary(self):
        """TC-14: Single-issue image at borderline of fair/poor.
        Condition: len(issues) == 1 AND blur >= BLUR_THRESHOLD/2 AND contrast >= CONTRAST_THRESHOLD*0.625
        Exactly AT these secondary thresholds should still be 'fair'."""
        from handwriting_engine.quality import assess_image
        from handwriting_engine._constants import BLUR_THRESHOLD, CONTRAST_THRESHOLD
        # Use a real assess to verify the fair/poor logic boundary is correct
        # Create an image that's slightly low contrast (at the threshold boundary)
        # with high blur score — should be 'fair'
        img = Image.new("RGB", (400, 400), (255, 255, 255))
        draw = ImageDraw.Draw(img)
        # Draw very light lines (low contrast but above threshold)
        for y in range(0, 400, 40):
            draw.line([(0, y), (400, y)], fill=(200, 200, 200), width=1)
        fd, path = tempfile.mkstemp(suffix=".jpg")
        os.close(fd)
        img.save(path, "JPEG", quality=95)
        result = assess_image(path)
        os.unlink(path)
        assert result["quality"] in ("good", "fair", "poor")  # Must return valid tier


# ===========================================================================
# T4 — Historical Bug Patterns: off-by-one and logic inversions
# ===========================================================================

class TestHistoricalBugPatterns:
    """T4: Apply known bug archetypes to handwriting-engine functions."""

    def test_check_text_similarity_single_text(self):
        """TC-15: check_text_similarity with 1 text — must return [] (guard clause)."""
        from handwriting_engine.integrity import check_text_similarity
        result = check_text_similarity(["single submission text here"])
        assert result == [], f"Single text should return [], got {result}"

    def test_check_text_similarity_empty_list(self):
        """TC-16: Empty list — must return [] without IndexError."""
        from handwriting_engine.integrity import check_text_similarity
        result = check_text_similarity([])
        assert result == []

    def test_check_text_similarity_identical_texts(self):
        """TC-17: Two identical texts — must return one pair with score 1.0."""
        from handwriting_engine.integrity import check_text_similarity
        text = "the mitochondria is the powerhouse of the cell"
        result = check_text_similarity([text, text], threshold=0.85)
        assert len(result) == 1
        assert result[0][2] == 1.0

    def test_ngrams_fewer_tokens_than_n(self):
        """TC-18: Off-by-one: _ngrams with len(tokens) < n returns {tuple(tokens)}."""
        from handwriting_engine.integrity import _ngrams
        # 2 tokens, n=3 → returns {('a', 'b')} (the single partial n-gram)
        result = _ngrams(["a", "b"], n=3)
        assert result == {("a", "b")}, f"Expected {{('a','b')}}, got {result}"

    def test_ngrams_empty_tokens(self):
        """TC-19: _ngrams with empty list → empty set (not {tuple([])} = {()})."""
        from handwriting_engine.integrity import _ngrams
        result = _ngrams([], n=3)
        assert result == set()

    def test_jaccard_both_empty_returns_zero(self):
        """TC-20: _jaccard({}, {}) == 0.0 per contract."""
        from handwriting_engine.integrity import _jaccard
        result = _jaccard(set(), set())
        assert result == 0.0

    def test_jaccard_one_empty_one_nonempty(self):
        """TC-21: _jaccard({}, {a,b}) — union is non-empty, intersection is 0."""
        from handwriting_engine.integrity import _jaccard
        result = _jaccard(set(), {"a", "b"})
        assert result == 0.0

    def test_correct_domain_terms_word_boundary_prefix_handling(self):
        """TC-22: Word with leading punctuation — e.g. '(mitocondria)'.
        The prefix-stripping loop should preserve '(' and suffix ')'."""
        from handwriting_engine.postprocess import correct_domain_terms
        result = correct_domain_terms("see (mitocondria) here", "biology")
        # mitocondria → mitochondria, but surrounding parens must be preserved
        assert "mitochondria" in result
        assert "(" in result or "mitochondria" in result

    def test_edit_distance_candidates_very_short_word(self):
        """TC-23: _edit_distance_1_candidates on 1-char word — splits create empties."""
        from handwriting_engine.postprocess import _edit_distance_1_candidates, _BIOLOGY_TERMS
        # Should not crash on 1-char word
        candidates = _edit_distance_1_candidates("a", _BIOLOGY_TERMS)
        assert isinstance(candidates, list)


# ===========================================================================
# T5 — Chaos Engineering: resource exhaustion and degenerate inputs
# ===========================================================================

class TestChaosEngineering:
    """T5: Stress with very large inputs, empty collections, etc."""

    def test_correct_domain_terms_very_long_text(self):
        """TC-24: correct_domain_terms with 10,000 word input — no crash/OOM."""
        from handwriting_engine.postprocess import correct_domain_terms
        long_text = ("the mitocondria is important " * 500).strip()
        result = correct_domain_terms(long_text, "biology")
        assert isinstance(result, str)
        assert len(result) > 0

    def test_check_text_similarity_many_identical_submissions(self):
        """TC-25: 50 identical texts — O(n^2) comparisons, must finish."""
        from handwriting_engine.integrity import check_text_similarity
        text = "the mitochondria is the powerhouse of the cell"
        texts = [text] * 50
        result = check_text_similarity(texts, threshold=0.85)
        # 50*49/2 = 1225 pairs — all should be flagged
        assert len(result) == 1225

    def test_batch_assess_empty_directory(self):
        """TC-26: batch_assess on a directory with no image files."""
        from handwriting_engine.quality import batch_assess
        tmpdir = tempfile.mkdtemp()
        # Create a non-image file to ensure it's ignored
        with open(os.path.join(tmpdir, "notes.txt"), "w") as f:
            f.write("not an image")
        result = batch_assess(tmpdir)
        assert result == {}, f"Empty image dir should return {{}}, got {result}"

    def test_flag_anomalies_empty_submissions(self):
        """TC-27: flag_anomalies with empty list."""
        from handwriting_engine.integrity import flag_anomalies
        result = flag_anomalies([])
        assert result == []

    def test_correct_domain_terms_only_punctuation(self):
        """TC-28: Text that is only punctuation — no words, no crash."""
        from handwriting_engine.postprocess import correct_domain_terms
        result = correct_domain_terms("!!! ??? ... ,,,", "biology")
        assert isinstance(result, str)

    def test_detect_skew_very_large_image_performance(self):
        """TC-29: detect_skew on a 3000x4000 image — must downsample and finish quickly."""
        from handwriting_engine.quality import detect_skew
        img = Image.new("RGB", (3000, 4000), (255, 255, 255))
        draw = ImageDraw.Draw(img)
        for y in range(0, 4000, 50):
            draw.line([(0, y), (3000, y)], fill=(0, 0, 0), width=1)
        fd, path = tempfile.mkstemp(suffix=".jpg")
        os.close(fd)
        img.save(path, "JPEG", quality=60)
        import time
        t0 = time.time()
        angle = detect_skew(path)
        elapsed = time.time() - t0
        os.unlink(path)
        assert isinstance(angle, float)
        assert elapsed < 10.0, f"detect_skew took {elapsed:.1f}s on large image (expected <10s)"


# ===========================================================================
# T6 — Invariant Testing: mathematical properties
# ===========================================================================

class TestInvariants:
    """T6: Mathematical invariants that must hold across all inputs."""

    def test_jaccard_symmetry(self):
        """TC-30: Jaccard(A,B) == Jaccard(B,A) always."""
        from handwriting_engine.integrity import _jaccard
        a = {"apple", "banana", "cherry"}
        b = {"banana", "cherry", "date"}
        assert _jaccard(a, b) == _jaccard(b, a)

    def test_jaccard_bounded_zero_to_one(self):
        """TC-31: Jaccard result must always be in [0, 1]."""
        from handwriting_engine.integrity import _jaccard
        import random
        for _ in range(20):
            size = random.randint(0, 10)
            a = set(range(size))
            b = set(range(random.randint(0, 10)))
            score = _jaccard(a, b)
            assert 0.0 <= score <= 1.0, f"Jaccard out of bounds: {score}"

    def test_contrast_bounded_zero_to_one(self):
        """TC-32: assess_contrast must always return a value in [0, 1]."""
        from handwriting_engine.quality import assess_contrast
        test_cases = [
            Image.new("RGB", (200, 200), (0, 0, 0)),
            Image.new("RGB", (200, 200), (255, 255, 255)),
            Image.new("RGB", (200, 200), (128, 128, 128)),
        ]
        for img in test_cases:
            score = assess_contrast(img)
            assert 0.0 <= score <= 1.0, f"contrast out of bounds: {score}"

    def test_similarity_threshold_monotone(self):
        """TC-33: Lower threshold should flag >= pairs as higher threshold."""
        from handwriting_engine.integrity import check_text_similarity
        texts = [
            "the mitochondria powers the cell",
            "the mitochondria powers all cells",
            "completely unrelated biology content here today",
        ]
        pairs_loose = check_text_similarity(texts, threshold=0.1)
        pairs_strict = check_text_similarity(texts, threshold=0.9)
        assert len(pairs_loose) >= len(pairs_strict), (
            "Lower threshold must flag >= pairs than strict threshold"
        )

    def test_assess_image_issues_quality_consistency(self):
        """TC-34: If issues is empty, quality must be 'good'."""
        from handwriting_engine.quality import assess_image
        # Sharp, high-contrast, normal brightness image
        img = Image.new("RGB", (400, 400), (240, 240, 240))
        draw = ImageDraw.Draw(img)
        for y in range(0, 400, 10):
            draw.line([(0, y), (400, y)], fill=(10, 10, 10), width=2)
        fd, path = tempfile.mkstemp(suffix=".jpg")
        os.close(fd)
        img.save(path, "JPEG", quality=95)
        result = assess_image(path)
        os.unlink(path)
        if result["issues"] == [] or result["issues"] == ["skewed"]:
            # Should be 'good' or 'fair' at worst
            assert result["quality"] in ("good", "fair"), (
                f"No issues but quality={result['quality']}"
            )


# ===========================================================================
# T7 — Scale Breaking: extreme numeric values
# ===========================================================================

class TestScaleBreaking:
    """T7: Extreme parameter values."""

    def test_compute_answer_regions_zero_questions(self):
        """TC-35: compute_answer_regions with num_questions=0 — must return empty dict."""
        from handwriting_engine.crop import compute_answer_regions, AnswerSheetLayout
        regions = compute_answer_regions(2550, 3300, AnswerSheetLayout(), 0)
        assert regions == {}, f"0 questions should return {{}}, got {regions}"

    def test_compute_answer_regions_single_question(self):
        """TC-36: compute_answer_regions with num_questions=1."""
        from handwriting_engine.crop import compute_answer_regions, AnswerSheetLayout
        regions = compute_answer_regions(2550, 3300, AnswerSheetLayout(), 1)
        assert 1 in regions
        x1, y1, x2, y2 = regions[1]
        assert x1 >= 0 and y1 >= 0
        assert x2 <= 2550 and y2 <= 3300

    def test_compute_answer_regions_very_small_image(self):
        """TC-37: compute_answer_regions on a 10x10 image — pixel values may go negative
        before clamping. Verify clamping logic works."""
        from handwriting_engine.crop import compute_answer_regions, AnswerSheetLayout
        regions = compute_answer_regions(10, 10, AnswerSheetLayout(), 5)
        for q, (x1, y1, x2, y2) in regions.items():
            assert x1 >= 0, f"Q{q}: x1={x1} went negative"
            assert y1 >= 0, f"Q{q}: y1={y1} went negative"
            assert x2 <= 10, f"Q{q}: x2={x2} exceeds width"
            assert y2 <= 10, f"Q{q}: y2={y2} exceeds height"

    def test_compute_answer_regions_question_51_right_column(self):
        """TC-38: Questions > questions_per_column go to right column.
        Question 26 (first right column) should use right_x_start/right_x_end."""
        from handwriting_engine.crop import compute_answer_regions, AnswerSheetLayout
        layout = AnswerSheetLayout()
        regions = compute_answer_regions(2550, 3300, layout, 26)
        q26 = regions[26]
        x1_26, _, x2_26, _ = q26
        q1 = regions[1]
        x1_1, _, x2_1, _ = q1
        # Q26 x-range should be right of Q1's x-range (approximately)
        assert x1_26 > x1_1, "Q26 should be in the right column (x_start > Q1 x_start)"

    def test_validate_and_prepare_image_max_long_side_zero(self):
        """TC-39: max_long_side=0 — resize ratio becomes inf, may cause crash."""
        from handwriting_engine.optimize import validate_and_prepare_image
        path = _solid_image(size=(100, 100))
        try:
            result = validate_and_prepare_image(path, max_long_side=0)
            # If it doesn't crash, it should return None or a valid result
            assert result is None or isinstance(result, tuple)
        except (ZeroDivisionError, ValueError):
            pass  # Acceptable to raise on degenerate input
        finally:
            os.unlink(path)

    def test_proven_enhance_upscale_factor_8(self):
        """TC-40: proven_enhance with upscale=8 — maximum allowed; should not crash."""
        from handwriting_engine.enhance import proven_enhance
        path = _solid_image(size=(50, 50))
        try:
            result = proven_enhance(path, upscale=8)
            assert os.path.exists(result)
        except Exception as e:
            pytest.fail(f"proven_enhance with upscale=8 raised: {e}")
        finally:
            if os.path.exists(path):
                os.unlink(path)

    def test_proven_enhance_upscale_factor_9_raises(self):
        """TC-41: proven_enhance with upscale=9 — must raise ValueError per contract."""
        from handwriting_engine.enhance import proven_enhance
        path = _solid_image(size=(50, 50))
        with pytest.raises(ValueError, match="too large"):
            proven_enhance(path, upscale=9)
        os.unlink(path)


# ===========================================================================
# T8 — Adversarial Payloads: injection / special characters / encoding
# ===========================================================================

class TestAdversarialPayloads:
    """T8: Malicious / edge-case string inputs passed as DATA to functions."""

    def test_correct_domain_terms_null_bytes(self):
        """TC-42: Text containing null bytes."""
        from handwriting_engine.postprocess import correct_domain_terms
        result = correct_domain_terms("hello\x00world", "biology")
        assert isinstance(result, str)

    def test_correct_domain_terms_unicode_bidirectional(self):
        """TC-43: Unicode right-to-left override characters."""
        from handwriting_engine.postprocess import correct_domain_terms
        text = "the \u202emitocondria\u202c is here"
        result = correct_domain_terms(text, "biology")
        assert isinstance(result, str)

    def test_correct_domain_terms_emoji(self):
        """TC-44: Emoji characters in transcription — common in student work."""
        from handwriting_engine.postprocess import correct_domain_terms
        result = correct_domain_terms("the mitocondria 🦠 is the powerhouse", "biology")
        assert isinstance(result, str)
        assert "mitochondria" in result

    def test_check_text_similarity_very_long_texts(self):
        """TC-45: Two 10,000-word texts — must complete without timeout."""
        from handwriting_engine.integrity import check_text_similarity
        text_a = ("the mitochondria is important " * 334).strip()
        text_b = ("the chloroplast converts light " * 334).strip()
        result = check_text_similarity([text_a, text_b], threshold=0.85)
        assert isinstance(result, list)

    def test_assess_image_path_with_spaces(self):
        """TC-46: Image path containing spaces — must not cause shell injection."""
        from handwriting_engine.quality import assess_image
        tmpdir = tempfile.mkdtemp()
        path = os.path.join(tmpdir, "my image with spaces.jpg")
        img = Image.new("RGB", (100, 100), (200, 200, 200))
        img.save(path, "JPEG")
        result = assess_image(path)
        os.unlink(path)
        os.rmdir(tmpdir)
        assert isinstance(result, dict)
        assert "quality" in result

    def test_enhance_image_unknown_strategy_raises_value_error(self):
        """TC-47: enhance_image with completely unknown strategy name."""
        from handwriting_engine.enhance import enhance_image
        path = _solid_image()
        with pytest.raises(ValueError, match="Unknown enhancement strategy"):
            enhance_image(path, strategy="__injection_test__; rm -rf /")
        os.unlink(path)

    def test_correct_domain_terms_newlines_in_text(self):
        """TC-48: Text with embedded newlines — split() by default splits on
        all whitespace including newlines, so words are extracted correctly."""
        from handwriting_engine.postprocess import correct_domain_terms
        result = correct_domain_terms("the\nmitocondria\nis\nimportant", "biology")
        assert "mitochondria" in result

    def test_batch_assess_path_traversal_attempt(self):
        """TC-49: batch_assess with path containing ../ traversal — must only
        process files within the given directory, not escape it."""
        from handwriting_engine.quality import batch_assess
        # Use a temp dir as safe boundary
        tmpdir = tempfile.mkdtemp()
        # Create a valid image file
        img_path = os.path.join(tmpdir, "page.jpg")
        Image.new("RGB", (100, 100), (200, 200, 200)).save(img_path, "JPEG")
        result = batch_assess(tmpdir)
        os.unlink(img_path)
        os.rmdir(tmpdir)
        assert all(tmpdir in k for k in result.keys()), (
            "batch_assess should only return paths within the given directory"
        )


# ===========================================================================
# T1+T2 Interaction: recommend_enhancement_params logic
# ===========================================================================

class TestRecommendEnhancementParams:
    """Interaction Prober: recommend_enhancement_params has complex if/elif chains."""

    def test_faint_ink_overrides_quality_good(self):
        """TC-50: faint_ink=True even when quality='good' — should override to 'contrast'."""
        from handwriting_engine.quality import recommend_enhancement_params
        assessment = {
            "quality": "good",
            "issues": [],
            "faint_ink": True,
        }
        params = recommend_enhancement_params(assessment)
        # faint_ink check now comes BEFORE the quality=='good' early return,
        # so faint_ink=True correctly overrides the good-quality short-circuit.
        assert params.get("strategy") == "adaptive", (
            "faint_ink=True must override quality='good' and return adaptive params"
        )
        assert params.get("contrast") is True
        assert params.get("sharpen") is False

    def test_blurry_and_faint_ink_together(self):
        """TC-51: Both 'blurry' and faint_ink=True — should use faint_ink branch."""
        from handwriting_engine.quality import recommend_enhancement_params
        assessment = {
            "quality": "fair",
            "issues": ["blurry"],
            "faint_ink": True,
        }
        params = recommend_enhancement_params(assessment)
        # faint_ink check comes FIRST in the if/elif chain, so it wins over blurry
        assert params.get("contrast") is True, (
            "faint_ink=True should enable contrast treatment even with blurry issue"
        )
        # AND: faint_ink path explicitly comments "NO sharpen for faint"
        # If sharpen were enabled here, that's a bug
        assert params.get("sharpen") is False, (
            "faint_ink path must NOT enable sharpen (amplifies noise)"
        )

    def test_multiple_issues_fallthrough(self):
        """TC-52: Image with both 'blurry' and 'low_contrast' — hits 'else' branch."""
        from handwriting_engine.quality import recommend_enhancement_params
        assessment = {
            "quality": "poor",
            "issues": ["blurry", "low_contrast"],
            "faint_ink": False,
        }
        params = recommend_enhancement_params(assessment)
        assert params.get("strategy") == "adaptive"
        assert params.get("denoise") is True
        assert params.get("sharpen") is True
        assert params.get("contrast") is True

    def test_too_dark_and_blurry_uses_else_branch(self):
        """TC-53: too_dark + blurry — hits else (multiple issues) branch."""
        from handwriting_engine.quality import recommend_enhancement_params
        assessment = {
            "quality": "poor",
            "issues": ["too_dark", "blurry"],
            "faint_ink": False,
        }
        params = recommend_enhancement_params(assessment)
        # too_dark is not explicitly handled when combined with blurry —
        # falls to the else branch (multiple issues)
        assert params.get("strategy") == "adaptive"

    def test_skewed_issue_alone_not_handled(self):
        """TC-54: 'skewed' alone as issue — no explicit branch, falls to else."""
        from handwriting_engine.quality import recommend_enhancement_params
        assessment = {
            "quality": "fair",
            "issues": ["skewed"],
            "faint_ink": False,
        }
        params = recommend_enhancement_params(assessment)
        # 'skewed' alone is not explicitly handled by any if/elif branch in
        # recommend_enhancement_params — falls to else: multiple issues full treatment
        # This is a design gap: skewed-only images get full treatment unnecessarily
        assert isinstance(params, dict)


# ===========================================================================
# T3+T6: _postprocess_output edge cases
# ===========================================================================

class TestPostprocessEdgeCases:
    """Interaction Prober: _postprocess_output has complex multi-pass regex."""

    def test_postprocess_preamble_consumes_entire_text(self):
        """TC-55: If preamble stripping removes ALL content, must return empty string."""
        from handwriting_engine.vision import _postprocess_output
        # Text where the preamble IS the entire text
        text = "Here is the transcribed text:\n"
        result = _postprocess_output(text)
        # After stripping preamble, nothing remains
        assert result == "" or isinstance(result, str)

    def test_postprocess_preamble_regex_anchored_to_start(self):
        """TC-56: Preamble regex must only match at START of string (anchored).
        If 'Here is' appears mid-text, it should NOT be stripped."""
        from handwriting_engine.vision import _postprocess_output
        text = "The student wrote: here is the answer\nActual: mitosis"
        result = _postprocess_output(text)
        # "here is" mid-line shouldn't strip — preamble regex starts with ^
        assert "mitosis" in result

    def test_postprocess_triple_repeated_line_kept_twice(self):
        """TC-57: Deduplication: lines appearing 3+ times are reduced to 2.
        Exactly 2 repetitions must NOT be deduplicated."""
        from handwriting_engine.vision import _postprocess_output
        text = "The answer\nThe answer\nDone"
        result = _postprocess_output(text)
        # 2 repetitions should be preserved
        assert result.count("The answer") == 2

    def test_postprocess_markdown_italic_inside_word(self):
        """TC-58: Italic regex _word_ must not corrupt intra-word underscores like
        variable_name_here."""
        from handwriting_engine.vision import _postprocess_output
        text = "The variable_name is important"
        result = _postprocess_output(text)
        assert "variable_name" in result, (
            "Italic regex should not corrupt variable_name underscores"
        )

    def test_postprocess_trailing_regex_middle_of_content(self):
        """TC-59: 'Note:' in the MIDDLE of content should not trigger trailing strip."""
        from handwriting_engine.vision import _postprocess_output
        text = "Note: the pH is 7.4\nthe temperature was 37C\nthe result was positive"
        result = _postprocess_output(text)
        # "Note:" is at line start but is the FIRST line, not a trailing line
        # _TRAILING_RE matches \nNote:... so it only fires if Note: appears after \n
        # In this case it's the very first line → no leading \n → won't match
        assert "7.4" in result or "Note" in result

    def test_postprocess_no_trailing_newline_preservation(self):
        """TC-60: Output should not have trailing whitespace."""
        from handwriting_engine.vision import _postprocess_output
        text = "The mitochondria\nNote: hard to read\n\n"
        result = _postprocess_output(text)
        assert result == result.strip() or result == ""


# ===========================================================================
# T1+T7: optimize module boundary tests
# ===========================================================================

class TestOptimizeBoundaries:
    """Boundary Hunter: validate_and_prepare_image and batch_pages_by_size."""

    def test_validate_nonexistent_path_returns_none(self):
        """TC-61: Non-existent path returns None (not raises)."""
        from handwriting_engine.optimize import validate_and_prepare_image
        result = validate_and_prepare_image("/absolutely/not/here.jpg")
        assert result is None

    def test_validate_empty_file_returns_none(self):
        """TC-62: Zero-byte file returns None."""
        from handwriting_engine.optimize import validate_and_prepare_image
        fd, path = tempfile.mkstemp(suffix=".jpg")
        os.close(fd)
        result = validate_and_prepare_image(path)
        os.unlink(path)
        assert result is None

    def test_build_image_blocks_skips_bad_page(self):
        """TC-63: build_image_blocks skips non-existent pages gracefully, returning
        an empty list. Callers (vision.py) handle the empty-list case."""
        from handwriting_engine.optimize import build_image_blocks
        pages = [{"path": "/not/here.jpg", "page_number": 1}]
        result = build_image_blocks(pages)
        assert result == []

    def test_batch_pages_empty_input_returns_empty(self):
        """TC-64: batch_pages_by_size with empty pages list returns []."""
        from handwriting_engine.optimize import batch_pages_by_size
        result = batch_pages_by_size([])
        assert result == []

    def test_is_blank_page_nonexistent_returns_false(self):
        """TC-65: is_blank_page returns False on non-existent path."""
        from handwriting_engine.optimize import is_blank_page
        result = is_blank_page("/not/here.jpg")
        assert result is False

    def test_is_blank_page_white_image(self):
        """TC-66: Pure white image must be detected as blank."""
        from handwriting_engine.optimize import is_blank_page
        path = _solid_image(color=(255, 255, 255), size=(300, 300))
        result = is_blank_page(path)
        os.unlink(path)
        assert result is True, "Pure white image should be detected as blank"

    def test_is_blank_page_black_image_not_blank(self):
        """TC-67: Pure black image must NOT be detected as blank (dark != blank)."""
        from handwriting_engine.optimize import is_blank_page
        path = _solid_image(color=(0, 0, 0), size=(300, 300))
        result = is_blank_page(path)
        os.unlink(path)
        assert result is False, "Black image must not be treated as blank"

    def test_get_adaptive_settings_page_count_zero(self):
        """TC-68: get_adaptive_settings(0) — 0 <= 15, should return tier 1."""
        from handwriting_engine.optimize import get_adaptive_settings
        dpi, quality, max_long_side = get_adaptive_settings(0)
        assert dpi == 200 and quality == 85

    def test_get_adaptive_settings_huge_page_count(self):
        """TC-69: get_adaptive_settings(999) — should hit the last tier."""
        from handwriting_engine.optimize import get_adaptive_settings
        dpi, quality, max_long_side = get_adaptive_settings(999)
        assert dpi == 100 and quality == 70

    def test_get_adaptive_settings_boundary_15_pages(self):
        """TC-70: get_adaptive_settings(15) — exactly at tier 1 boundary."""
        from handwriting_engine.optimize import get_adaptive_settings
        dpi, quality, max_long_side = get_adaptive_settings(15)
        assert dpi == 200, f"page_count=15 should be in tier 1 (dpi=200), got {dpi}"

    def test_get_adaptive_settings_boundary_16_pages(self):
        """TC-71: get_adaptive_settings(16) — one above tier 1, must be tier 2."""
        from handwriting_engine.optimize import get_adaptive_settings
        dpi, quality, max_long_side = get_adaptive_settings(16)
        assert dpi == 150, f"page_count=16 should be in tier 2 (dpi=150), got {dpi}"


# ===========================================================================
# T2+T6: detect_skew edge cases
# ===========================================================================

class TestDetectSkewEdgeCases:
    """Contract violations and invariants for detect_skew."""

    def test_detect_skew_nonexistent_path_returns_zero(self):
        """TC-72: detect_skew with bad path returns 0.0 (safe default)."""
        from handwriting_engine.quality import detect_skew
        result = detect_skew("/not/here.jpg")
        assert result == 0.0

    def test_detect_skew_white_image_returns_zero(self):
        """TC-73: Blank white image — no ink pixels → no meaningful skew angle."""
        from handwriting_engine.quality import detect_skew
        path = _solid_image(color=(255, 255, 255), size=(200, 200))
        result = detect_skew(path)
        os.unlink(path)
        # A blank image has zero variance at every angle — should return 0.0
        assert result == 0.0, f"Blank image skew should be 0.0, got {result}"

    def test_detect_skew_result_within_test_range(self):
        """TC-74: detect_skew tests angles -5 to +5 degrees only. Result must be
        within that range."""
        from handwriting_engine.quality import detect_skew
        path = _striped_image(size=(400, 400))
        result = detect_skew(path)
        os.unlink(path)
        assert -5.25 <= result <= 5.25, f"detect_skew returned out-of-range: {result}"

    def test_detect_skew_unused_variable_pixels(self):
        """TC-75: Dead variable pixels = gray.load() was removed (fix applied).
        Verify detect_skew no longer assigns the unused variable."""
        import inspect
        from handwriting_engine.quality import detect_skew
        source = inspect.getsource(detect_skew)
        assert "pixels = gray.load()" not in source, (
            "pixels = gray.load() is dead code — should have been removed"
        )


# ===========================================================================
# T5+T8: classify_handwriting_style edge cases
# ===========================================================================

class TestClassifyHandwritingStyle:
    """Scale Breaker + Adversarial: classify_handwriting_style."""

    def test_classify_blank_image_returns_mixed(self):
        """TC-76: Blank white image — no ink pixels → run_lengths=[] → 'mixed'."""
        from handwriting_engine.quality import classify_handwriting_style
        path = _solid_image(color=(255, 255, 255), size=(200, 200))
        result = classify_handwriting_style(path)
        os.unlink(path)
        assert result == "mixed", f"Blank image should classify as 'mixed', got {result}"

    def test_classify_all_black_image(self):
        """TC-77: All-black image — all pixels are 'ink'. Threshold based on mean*0.75.
        If all pixels are 0, mean=0, threshold=0 → pixels are NOT < 0 → no ink runs.
        This is a degenerate case — function may return 'mixed'."""
        from handwriting_engine.quality import classify_handwriting_style
        path = _solid_image(color=(0, 0, 0), size=(200, 200))
        result = classify_handwriting_style(path)
        os.unlink(path)
        # threshold = mean * 0.75 = 0 * 0.75 = 0. Pixels are NOT < 0, so run_lengths=[]
        # → returns 'mixed'
        assert result in ("cursive", "print", "mixed")

    def test_classify_nonexistent_path_returns_mixed(self):
        """TC-78: Non-existent path returns 'mixed' (safe default)."""
        from handwriting_engine.quality import classify_handwriting_style
        result = classify_handwriting_style("/not/here.jpg")
        assert result == "mixed"

    def test_classify_large_image_downsampled(self):
        """TC-79: Image wider than 600px — must be downsampled before analysis."""
        from handwriting_engine.quality import classify_handwriting_style
        img = Image.new("RGB", (1200, 800), (255, 255, 255))
        draw = ImageDraw.Draw(img)
        # Draw horizontal lines (simulate print text)
        for y in range(0, 800, 30):
            draw.line([(0, y), (1200, y)], fill=(0, 0, 0), width=2)
        fd, path = tempfile.mkstemp(suffix=".jpg")
        os.close(fd)
        img.save(path, "JPEG", quality=95)
        result = classify_handwriting_style(path)
        os.unlink(path)
        assert result in ("cursive", "print", "mixed")


# ===========================================================================
# T2: flag_anomalies contract violations
# ===========================================================================

class TestFlagAnomaliesContract:
    """Contract: flag_anomalies missing 'name' or 'text' keys."""

    def test_flag_anomalies_missing_name_key(self):
        """TC-80: Submission dict without 'name' key — uses fallback 'submission_N'."""
        from handwriting_engine.integrity import flag_anomalies
        subs = [
            {"text": "the mitochondria is the powerhouse of the cell"},
            {"text": "the mitochondria is the powerhouse of the cell"},
        ]
        result = flag_anomalies(subs)
        assert isinstance(result, list)
        # Should not KeyError
        for item in result:
            assert "name" in item

    def test_flag_anomalies_missing_text_key(self):
        """TC-81: Submission without 'text' key — .get("text", "") fallback."""
        from handwriting_engine.integrity import flag_anomalies
        subs = [
            {"name": "student_a"},  # no text key
            {"name": "student_b"},  # no text key
        ]
        result = flag_anomalies(subs)
        # Should not crash — text defaults to ""
        assert isinstance(result, list)

    def test_flag_anomalies_typed_detection_missing_image(self):
        """TC-82: Submission with image_path pointing to nonexistent file."""
        from handwriting_engine.integrity import flag_anomalies
        subs = [
            {"name": "student_a", "text": "hello", "image_path": "/not/here.jpg"},
        ]
        result = flag_anomalies(subs)
        assert isinstance(result, list)  # Must not crash

    def test_check_text_similarity_threshold_zero(self):
        """TC-83: threshold=0.0 — all non-identical pairs flagged (any overlap).
        Even single word overlap triggers."""
        from handwriting_engine.integrity import check_text_similarity
        texts = ["apple banana cherry", "grape mango apple"]
        result = check_text_similarity(texts, threshold=0.0)
        # With threshold=0, score >= 0.0 always, so flagged
        assert len(result) >= 1

    def test_check_text_similarity_threshold_exactly_one(self):
        """TC-84: threshold=1.0 — only perfect matches flagged."""
        from handwriting_engine.integrity import check_text_similarity
        texts = [
            "the mitochondria is the powerhouse of the cell",
            "the mitochondria is the powerhouse of the cell",
            "a completely different sentence with no overlap",
        ]
        result = check_text_similarity(texts, threshold=1.0)
        # Only the identical pair (0,1) should be flagged
        assert len(result) == 1
        assert result[0][:2] == (0, 1)
